image: docker:stable

services:
  - docker:dind

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t minha-imagem .
    - docker images
    - docker tag minha-imagem littlenogueira/minha-imagem:latest
    - docker push littlenogueira/minha-imagem:latest
