build-image:
  image: docker:stable
  stage: .pre
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t minha-imagem .
    - docker images
    - docker tag minha-imagem littlenogueira/minha-imagem:latest
    - docker push littlenogueira/minha-imagem:latest

build-project:
  image: littlenogueira/minha-imagem:latest
  stage: build
  services:
    - docker:dind
    - mysql:5.7
  variables:
    MYSQL_USER: $DB_USER
    MYSQL_PASSWORD: $DB_PASSWORD
    MYSQL_DATABASE: $DB_NAME
    MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD

    DB_NAME: $DB_NAME
    DB_USER: $DB_USER
    DB_PASSWORD: $DB_PASSWORD
    DB_PORT: '3306'
    DB_HOST: 'mysql'
    SECRET_KEY: $DB_SECRET_KEY
  dependencies:
    - build-image
  script:
    - python manage.py makemigrations
    - python manage.py migrate
