# build-image:
#   image: docker:stable
#   stage: .pre
#   services:
#     - docker:dind
#   before_script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#   script:
#     - docker build -t minha-imagem .
#     - docker images
#     - docker tag minha-imagem littlenogueira/minha-imagem:latest
#     - docker push littlenogueira/minha-imagem:latest

# build-project:
#   image: littlenogueira/minha-imagem:latest
#   stage: build
#   services:
#     - mysql:5.7
#   variables:
#     MYSQL_USER: $DB_USER
#     MYSQL_PASSWORD: $DB_PASSWORD
#     MYSQL_DATABASE: $DB_NAME
#     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD

#     DB_NAME: $DB_NAME
#     DB_USER: $DB_USER
#     DB_PASSWORD: $DB_PASSWORD
#     DB_PORT: '3306'
#     DB_HOST: 'mysql'
#     SECRET_KEY: $DB_SECRET_KEY
#   dependencies:
#     - build-image
#   script:
#     - python manage.py makemigrations
#     - python manage.py migrate

# test-unit:
#   image: littlenogueira/minha-imagem:latest
#   stage: test
#   services:
#     - mysql:5.7
#   variables:
#     MYSQL_USER: $DB_USER
#     MYSQL_PASSWORD: $DB_PASSWORD
#     MYSQL_DATABASE: $DB_NAME
#     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD

#     DB_NAME: $DB_NAME
#     DB_USER: $DB_USER
#     DB_PASSWORD: $DB_PASSWORD
#     DB_PORT: '3306'
#     DB_HOST: 'mysql'
#     SECRET_KEY: $DB_SECRET_KEY
#   dependencies:
#     - build-project
#   script:
#     - python -m unittest setUp


terraform-validate:
  stage: test
  image: 
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - systeminfo
    - cat terraform.rc
    - terraform init -input=false
    - terraform validate
    - terraform plan
    - terraform apply -auto-approve 
    - cat ip.txt

# terraform-deploy:
#   stage: deploy
#   image: 
#     name: hashicorp/terraform:light
#     entrypoint:
#       - '/usr/bin/env'
#       - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#       - 'AWS_SECRET_ACCESS_KEY=1++8bxEvukfJaOlLaY/lIfnQMIFMc1uU5LT/KsBn'
#       - 'AWS_ACCESS_KEY_ID=AKIA2R4UXIAXEM2753OX'
#   before_script:
#     - terraform --version
#     - terraform init
#   script:
#     - terraform apply -auto-approve 
